[package]
name = "mysteriouspants-throttle"
version = "0.1.0"
license = "BSD"
authors = ["Christopher R. Miller <xpm@mysteriouspants.com>"]
description = "Simple throttle implementation to make rate-limiting easy."

[dependencies]
